# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2024 Tristan Partin <tristan@partin.io>

version = 1
SPDX-HomePage = "https://github.com/return0software/gosplitsies"
SPDX-PackageName = "gosplitsies"

[[annotations]]
path = [
    ".vscode/copyright.code-snippets",
    "ui/package.json",
    "ui/package-lock.json",
]
precedence              = "override"
SPDX-FileCopyrightText  = "2024 Joseph Martinsen <joseph@martinsen.com>"
SPDX-License-Identifier = "AGPL-3.0-or-later"
