# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2024 Tristan Partin <tristan@partin.io>

name: Build Server

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.go"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gosplitsies
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version: stable

      - name: Install Just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh |
            bash -s -- --to /usr/local/bin

      - name: Build the Server
        run: |
          just debug
