# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2024 Tristan Partin <tristan@partin.io>

name: golangci-lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.go"

permissions:
  contents: read

jobs:
  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gosplitsies
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
