# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2024 Tristan Partin <tristan@partin.io>

name: REUSE

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  reuse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout splitsies
        uses: actions/checkout@v4

      - name: Lint
        uses: fsfe/reuse-action@v5
